### ISSUE TITLE
may got numpy error.

### ISSUE THREAD

**Issue by smingscript** [fjean/pymeanshift#12]
Hello! 
I recently updated my anaconda and it upgraded numpy version to 1.8.1.
and I got this error when I call "_pymeanshift.segment(image, spatial_radius, range_radius, min_density, speedup_level)" in pymeanshift.py to use "segment" function

Error: NotImplementedError: PyArray_FromDims: use PyArray_SimpleNew.

Is this due to the depency of numpy?

thank you!

**Comment by fjean** [comment]
Hi,

Thanks for reporting this. I think I have fix the problem, PyArray_FromDims is now deprecated, and we have to use PyArray_SimpleNew instead (in the C API of NumPy). This seems to work with old version of NumPy too.

Let me know if it works for you.

**Comment by smingscript** [comment]
It perfectly works for me! Thank you so much! :)

I'll close the issue :)
