### ISSUE TITLE
declare minimum segment size 

### ISSUE THREAD

**Issue by NinjaAtWork** [fjean/pymeanshift#16]
Hi
There is a way to define smallest segment size ?
as i play with parameters it will produce a few segment with very small size that i am unable to merge with a neighbor segment.
thanks for all

**Comment by fjean** [comment]
Hi,
Unfortunately I don't think the algorithm (and the C++ code) have the logic for defining a minimum region size.

**Comment by NinjaAtWork** [comment]
As in our case smallest (and biggest )segment size is needed 
At the other hand this algorithm provide so far best mean shift segmentation which we found 
It will cover more applications area if you can add this features
Thanks for this 😊
Best Regards

**Comment by fjean** [comment]
This would not be the mean shift algorithm anymore, it sounds more like a superpixel algorithm like SLIC; maybe that's what you would need in this case.

**Comment by NinjaAtWork** [comment]
in our case pms+postprocess is going to be better than python-SLIC which result (a little) Qubic
