### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by NinjaAtWork** [fjean/pymeanshift#18]
Hi
Using this great tool for a long time but recently with new win 10 OS setup, I can’t figure problem with Visual C++ 2008 express Prerequisite, wasn’t able to find the right pieces. installation wiki has wrong or 404 link. It can be fixed? Please

**Comment by fjean** [comment]
Hi, you are right, it seems that Visual C++ 2008 Express cannot be downloaded anymore from Microsoft website. Python 2.7 has reached its end of life, so if you can run your Python code on Python >= 3.5, that would be the best. For this, you can compile Pymeanshift with Visual Studio Community Edition 2015 or 2017.

**Comment by NinjaAtWork** [comment]
thanks .
