### ISSUE TITLE
merge regions

### ISSUE THREAD

**Issue by NinjaAtWork** [fjean/pymeanshift#19]
Hi
may i ask how i can merge/remove regions?
there is a few micro region produced over the image which i want to remove or merge.
thanks

**Comment by fjean** [comment]
Closing

**Comment by fjean** [comment]
The algorithm itself, as far as I know, doesn't allow that; you might want to filter with your own algorithm afterwards.

**Comment by NinjaAtWork** [comment]
Thanks 🙏
