### ISSUE TITLE
what does the parameter min_density actually mean? 

### ISSUE THREAD

**Issue by lifinger** [fjean/pymeanshift#4]
Only spatial radius hs and range radius hr are talked in the original paper, but it seems the min_density in the pymeanshift package does exert influence on the segmentation results. I am wondering what is the role of this parameter and why it is not mentioned in the original paper? The spatial radius and range radius used here is the same described in the original paper?

Thanks any guys providing any insights!

**Comment by naegelejd** [comment]
`min_density` is `M` in the paper, in the Image Segmentation section.
