### ISSUE TITLE
Where are the Clusters Locations?

### ISSUE THREAD

**Issue by Rana-ElRobi** [fjean/pymeanshift#6]
I applied the code on my image and i wanted to know the locations of each cluster to apply some operations on some clusters , where could i get them ?

![clusterslocation](https://cloud.githubusercontent.com/assets/8526569/22204856/d2922200-e17c-11e6-9408-c690f13022c2.png)

**Comment by codepujan** [comment]
Generally , You can get the clusters location Through the Connected Components process  , that is applied after the actual meanshift segmentation process   and before the  final  output . The author of this library  doesn't expose something from that middleware . So , I suppose : you'd have to tinker around in the c++ code somewhere for that . I also have the same issue .
