### ISSUE TITLE
Failed to build when 'bash build'

### ISSUE THREAD

**Issue by gaoyangyiqiao** [fjean/pymeanshift#7]
When `bash setup.py build` it will failed:
``    raise RuntimeError("Error: Failed to import Numpy ({}). Please check that Numpy is installed on your system.".format(exc))'`
Change it to `python setup.py build` and everything goes well

**Comment by ramatech87** [comment]
hi,
i tried to install the pymeanshift using the 
Windows (at the command prompt): bash cd path-to-pymeanshift-sources python setup.py build
But i am getting error "The system cannot find the specified path".
kindly tell me how to debug and use meanshift algorithm for image segmentation.

**Comment by gaoyangyiqiao** [comment]
@ramatech87 Have you set the right path of the path-to-pymeanshift-source?Drag the directory to the cmd and see it. What will happen if you run `python setup.py build`?
My procedure is 1. `cd path-to-the-source`2.`python setup.py build` and goes well

**Comment by ramatech87** [comment]
i am getting error 
"The system cannot find the path specified". 
kindly help me

**Comment by gaoyangyiqiao** [comment]
You may refer to stackoverflow like [this](https://stackoverflow.com/questions/46849585/pyspark-the-system-cannot-find-the-path-specified). I think it has no business with this repo, but something with your system python environment.

**Comment by ramatech87** [comment]
okay. Thanx alot.

**Comment by ZubairKhan001** [comment]
For Ubuntu **python setup.py build** and   **python setup.py install** work perfectly.
python can be replaced with python3 for python version 3.
