### ISSUE TITLE
Colorspace Specification

### ISSUE THREAD

**Issue by aradhyamathur** [fjean/pymeanshift#8]
I have a doubt regarding the returned segmented image. Is it in the LUV colorspace or does it return segmented image in the RGB colorspace ?

**Comment by fjean** [comment]
Sorry for the delay, I just saw this... hopefully it will be useful to someone, if not for you!

The input image must be RGB, and the output segmented image is also in RGB. The input RGB image is converted to LUV to perform the meanshift algorithm. The resulting segmented image if converted back to RGB.

See the file https://github.com/fjean/pymeanshift/blob/master/msImageProcessor.h

Hope this helps
